### ISSUE TITLE
get_value_in: support of float values

### ISSUE THREAD

**Issue by oblalex** [schematics/schematics#463]
`get_range_endpoints()` uses `random.randint()` to produce random numbers while creating mock objects.

The issue is that `FloatType` fails to create mock objects, if it has float values for `min_value` and `max_value` properties.

E.g., having field

``` python

delay = FloatType(
    min_value=1.0,
    max_value=30.0,
    default=10.0,
    required=True,
)
```

will raise an error

```ServerConfig.get_mock_object().to_primitive()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    ServerConfig.get_mock_object().to_primitive()
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/models.py", line 378, in get_mock_object
    values[name] = field.mock(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/base.py", line 323, in mock
    return self._mock(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/compound.py", line 115, in _mock
    return self.model_class.get_mock_object(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/models.py", line 378, in get_mock_object
    values[name] = field.mock(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/base.py", line 323, in mock
    return self._mock(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/compound.py", line 115, in _mock
    return self.model_class.get_mock_object(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/models.py", line 378, in get_mock_object
    values[name] = field.mock(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/base.py", line 323, in mock
    return self._mock(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/compound.py", line 115, in _mock
    return self.model_class.get_mock_object(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/models.py", line 378, in get_mock_object
    values[name] = field.mock(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/base.py", line 323, in mock
    return self._mock(context)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/base.py", line 450, in _mock
    return get_value_in(self.min_value, self.max_value)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/site-packages/schematics/types/base.py", line 71, in get_value_in
    *get_range_endpoints(min_length, max_length, padding, required_length))
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/random.py", line 218, in randint
    return self.randrange(a, b+1)
  File "/Users/alex/.virtualenvs/sandbox/lib/python3.4/random.py", line 182, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()
```

Obviously, `random.randint` cannot be used for creating random floats. `random.uniform` must do this job.

`get_value_in` is also used by `StringType` and so on. The most simple approach is to select random generator basing on type of `min_length` and `max_length` parameters, e.g.:

``` python

def get_value_in(min_length, max_length, padding=0, required_length=0):
    generator = (
        random.uniform
        if isinstance(min_length, float) or isinstance(max_length, float) else
        random.randint
    )
    return generator(
        *get_range_endpoints(min_length, max_length, padding, required_length))
```

But, IMHO, this is a bit dirty way. It's better to specify proper generator in type/field definition. This will also allow user to set own generator, e.g. from `faker` library.

Thanks

**Comment by oblalex** [comment]
Please, provide any feedback and I'll be able to create a pull request.

**Comment by lkraider** [comment]
Sorry for only getting to this now.

We should investigate refactoring the mock functionality so that we can plugin libs like hypothesis and faker.
