### ISSUE TITLE
DictType , ListType Error

### ISSUE THREAD

**Issue by rfyiamcool** [schematics/schematics#468]
I want know schematics(dictType, LIstType) usage ,Then why is it wrong ?

#### code: 
```
from schematics.models import Model
from schematics.types import IntType, StringType
from schematics.types.compound import DictType, ModelType, ListType


class DetailDTO(Model):
    notes = StringType()


class StandardDTO(Model):
    standard = ListType(ModelType(DetailDTO))


class FreightTemplatedDTO(Model):

    id = IntType(required=True)
    blob = DictType(ModelType(StandardDTO))


d = {
    'id': 3,
    'blob': {
    ¦   'standard': [
    ¦   ¦   'nima'
    ¦   ]
    }
}


f = FreightTemplatedDTO(d)
print f
```

bug , raise error ?  

```
Press ENTER or type command to continue
Traceback (most recent call last):
  File "f.py", line 31, in <module>
    f = FreightTemplatedDTO(d)
  File "/home/ruifengyun/miniconda2/envs/xcf/lib/python2.7/site-packages/schematics/models.py", line 242, in __init__
    self._data = self.convert(raw_data, strict=strict, mapping=deserialize_mapping)
  File "/home/ruifengyun/miniconda2/envs/xcf/lib/python2.7/site-packages/schematics/models.py", line 289, in convert
    return convert(self.__class__, raw_data, **kw)
  File "/home/ruifengyun/miniconda2/envs/xcf/lib/python2.7/site-packages/schematics/transforms.py", line 419, in convert
    partial=partial, strict=strict, mapping=mapping)
  File "/home/ruifengyun/miniconda2/envs/xcf/lib/python2.7/site-packages/schematics/transforms.py", line 119, in import_loop
    raise ModelConversionError(errors, data)
schematics.exceptions.ModelConversionError: {'blob': [u'Please use a mapping for this field or StandardDTO instance instead of list.']}

shell returned 1
```

### Thanks You ....

**Comment by rfyiamcool** [comment]
I know。。。

**Comment by fabouru1985** [comment]
What happened with this error? I'm having the same

**Comment by aleksej-paschenko** [comment]
I think that for this json models should be 
```python 

class StandardDTO(Model):
    standard = ListType(StringType)


class FreightTemplatedDTO(Model):

    id = IntType(required=True)
    blob = ModelType(StandardDTO)

```

or it should be 
```python
class DetailDTO(Model):
    notes = StringType()


class StandardDTO(Model):
    standard = ListType(ModelType(DetailDTO))


class FreightTemplatedDTO(Model):

    id = IntType(required=True)
    blob = DictType(ModelType(StandardDTO))


d = {
    'id': 3,
    'blob': {
       'the first key': {
           'standard' : [ { 'notes' : 'the first note'}]
       },
        'the second key': {
            'standard' : [ { 'notes' : 'the first note'}, {'notes' : 'the second one'}]
        }
    }
}

```
