### ISSUE TITLE
OrderedDict does NOT pickle

### ISSUE THREAD

**Issue by pombredanne** [schematics/schematics#474]
Why not use the stdlib OrderedDict ? I do not use pickle but multiprocessing does...
```
>>> from schematics.datastructures import OrderedDict
>>> import pickle
>>> p=pickle.dumps(OrderedDict(), pickle.HIGHEST_PROTOCOL)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 416, in save_reduce
    self._batch_setitems(dictitems)
  File "/usr/lib/python2.7/pickle.py", line 672, in _batch_setitems
    tmp.append(items.next())
AttributeError: 'list' object has no attribute 'next'
```

**Comment by ekampf** [comment]
Seems to work in latest version:
```
In [1]: from schematics.datastructures import OrderedDict

In [2]:     d = OrderedDict()
   ...:     d['z'] = 0
   ...:     d['first'] = 1
   ...:     d['second'] = 2
   ...:

In [3]: d
Out[3]: OrderedDict([('z', 0), ('first', 1), ('second', 2)])

In [4]: d.__dict__
Out[4]: {'_keys': ['z', 'first', 'second']}

In [5]: import pickle

In [6]: pickle.dumps(d)
Out[6]: "cschematics.datastructures\nOrderedDict\np0\n((lp1\n(lp2\nS'z'\np3\naI0\naa(lp4\nS'first'\np5\naI1\naa(lp6\nS'second'\np7\naI2\naatp8\nRp9\n."

In [7]: pickle.loads(pickle.dumps(d))
Out[7]: OrderedDict([('z', 0), ('first', 1), ('second', 2)])
```

**Comment by pombredanne** [comment]
Thanks! but why not use the stdlib collections ?

**Comment by lkraider** [comment]
We still support python 2.6 which doesn't have it.

**Comment by pombredanne** [comment]
@lkraider ok, but who uses 2.6 still? ;)

**Comment by lkraider** [comment]
I agree. We should probably target a new release without py2.6 support.
