### ISSUE TITLE
`role` parameter passed down to nested ModelType while data exporting

### ISSUE THREAD

**Issue by wonderbeyond** [schematics/schematics#533]
- schematics version: 2.0.1

---

Below is the test code:

```python
from schematics.models import Model
from schematics.types import StringType, IntType, ListType, ModelType
from schematics.transforms import blacklist, whitelist


class Group(Model):
    id = IntType()
    name = StringType()
    description = StringType()


class User(Model):
    id = StringType()
    name = StringType(required=True)
    password = StringType(required=True)
    groups = ListType(ModelType(Group))

    class Options:
        roles = {
            'public_view': blacklist('password'),
        }


# ---

user = User(dict(name='wonder'))
user.groups = [Group(dict(name='G1'))]

user.to_primitive('public_view')
```

which raises:

```python
Traceback (most recent call last):
  File "/home/wonder/lab/t.py", line 29, in <module>
    user.to_primitive('public_view')
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/models.py", line 305, in to_primitive
    return to_primitive(self._schema, self, role=role, app_data=app_data, **kwargs)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/transforms.py", line 437, in to_primitive
    return export_loop(cls, instance_or_dict, to_primitive_converter, **kwargs)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/transforms.py", line 278, in export_loop
    value = _field_converter(field, value, context)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/transforms.py", line 356, in __call__
    return self.func(*args)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/transforms.py", line 371, in to_primitive_converter
    return field.export(value, PRIMITIVE, context)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/types/compound.py", line 43, in export
    return self._export(value, format, context)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/types/compound.py", line 235, in _export
    shaped = self.field.export(value, format, context)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/types/compound.py", line 43, in export
    return self._export(value, format, context)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/types/compound.py", line 142, in _export
    return export_loop(model_class, value, context=context)
  File "/home/wonder/PyEnvs/xtpids/lib/python3.6/site-packages/schematics/transforms.py", line 260, in export_loop
    raise ValueError(error_msg % (schema.__name__, context.role))
ValueError: Group Model has no role "public_view"
```

**Comment by andrewsmedina** [comment]
I getting this behaviour too. This is a bug or a behaviour?
