### ISSUE TITLE
BaseType's has no attribute 'model_class'

### ISSUE THREAD

**Issue by ceandrade** [schematics/schematics#607]
I copied a simple code from X, to extract a JSON schema for Swagger. It turned out that the code does not run properly. SO, I did some debugging and I found that the property 'model_class' for lists are not working. This is some code for debugging:

```python
from schematics.types import StringType, IntType
from schematics.types.compound import ListType

my_list = ListType(IntType, required=True, min_size=1)
print(my_list.model_class)
```

```bash
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(my_list.model_class)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/schematics/types/compound.py", line 197, in model_class
    return self.field.model_class
AttributeError: 'IntType' object has no attribute 'model_class'
```

Indeed, this also happend for any BaseType, for nested lists, and so. For example:

```python
from schematics.types import StringType, IntType
from schematics.types.compound import ListType

my_list = ListType(ListType(ListType(IntType)), required=True, min_size=1)

print(my_list.model_class)
```

```bash
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(my_list.model_class)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/schematics/types/compound.py", line 197, in model_class
    return self.field.model_class
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/schematics/types/compound.py", line 197, in model_class
    return self.field.model_class
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/schematics/types/compound.py", line 197, in model_class
    return self.field.model_class
AttributeError: 'IntType' object has no attribute 'model_class'
```

This is another weird behaviour. Since we have nested listed, should 'model_class' return 'ListType' (or 'ListType(ListType(IntTyoe))') when called in the most external container? Why do we recurse here?

Should we implement 'model_class' for all BaseType's?

**Comment by ceandrade** [comment]
A simple is include 'model_class' property into BaseType's:

```python
class BaseType(object):

    @property
    def model_class(self):
        return self.typeclass
```

**Comment by lkraider** [comment]
Only the ModelType should have model_class property.

It's probably a bug in ListType to assume its field has that property
https://github.com/schematics/schematics/blob/3a144be0aa50f68a4da917e8d957b924dedf9a52/schematics/types/compound.py#L200
